config/routes.rb
Kajoo::Application.routes.draw do
  
  resources :issues do 
    #resource :solution
    resources :suggestions, :as => 'solutions'
    #, :as => 's'
    #disabled for now
    #match 'suggestions/:id/new'
    #match 'solutions/:id/vote' => 'solutions#vote', :as => 'vote_for_solution'
    #resources :comments
  end

  match 'issues/:id/vote' => 'issues#vote', :as => 'vote_for_issue'
  match 'issues/:id/mark_resolved' => 'issues#mark_resolved',:as => 'resolve_issue'
  resources :reports
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }
  match 'users/:userid' => 'users#show', :as => 'user'


  match 'index' => "pages#index", :as => 'index'
  match 'dashboard' => 'pages#dashboard', :as => 'dashboard'
  match 'home' => 'pages#home', :as => 'home'
  match 'contact' => 'pages#contact', :as => 'contact'
  match 'about' => 'pages#about', :as => 'about'
  match 'helpus' => 'pages#helpus', :as => 'helpus'
  match 'help' => 'pages#help', :as => 'help'

#  get "users/dashboard"
  
  resources :users
  
  match 'user/location' => 'users#location'
  match 'user/address' => 'users#address'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "pages#index"

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  versioned
  paginates_per 10
  default_scope order('vote_count desc')
  has_many :reports
  has_many :comments #XXX unused
  has_many :votes, :class_name => 'IssueVote'
  has_many :supporters, :through => :votes, :class_name => 'User', :uniq => true, :source => 'user'
  has_one :attributed, :class_name => 'User'
  has_one :resolver, :class_name => 'User'
  belongs_to :creator, :class_name => 'User'
  has_one :solution
  #has_many :solution_votes
  #has_many :suggestions, :through => :solution_votes, :class_name => 'Solution', :uniq => true, :source => 'solution'
  has_many :suggestions, :class_name => 'Solution', :uniq => true
  #validates_presence_of :reports
  acts_as_taggable_on :discovered
  #accepts_nested_attributes_for :reports, :allow_destroy => true
  accepts_nested_attributes_for :suggestions, :allow_destroy => true
   
  #open and resolved named scopes
  scope :open, where(:resolved => nil).order('vote_count desc') 
  scope :closed, where(:resolved => true).order('resolved_at desc') 
   
  geocoded_by :address, :latitude  => :lat, :longitude => :lon
  #_with_city_and_state, :latitude  => :lat, :longitude => :lon
   
  reverse_geocoded_by :lat, :lon do |obj, geo|
  #, :address => :location 
    obj.city = geo.city
    obj.zipcode = geo.postal_code
    obj.country_name = geo.country
    obj.country_code = geo.country_code 
    obj.street_address = geo.address
    obj.lat = geo.latitude
    obj.lon = geo.longitude
  end

#  after_validation :reverse_geocode
  before_save :set_resolved_at
  
  def self.find_similar(report)
    self.find_near_report(report)
  end
  def self.find_near_report(report)
    similar = self.near([report.lat, report.lon], 1)
  end
  def self.find_similar_tags_for_report(report)
    reports = self.find_near_report(report).map{|issue|issue.reports}
    reports.map{|r|r.categories}.flatten
    #similar.map{|s|s.reports.map{|r|r.categories}.flatten}.flatten.include? report.categ
    #similar
    similar.map{|issue|issue.reports.map{|r|r.categories.include? report.categories ? report : nil }.compact}.flatten
     
    #similar = self.near([report.lat, report.lon], 1)
    #reports = similar.map{|issue|issue.reports}
  end
  def add_vote_for_user(user)
    
    #unless(user.votes_remaining > 0)
      #throw VoteException.new('Not enough votes. Please return in a few hours to vote on more issues.')
    #end
    
   if(user.has_voted_for_issue?(self))
     throw VoteException.new('You cant vote twice for the same issue');
   end
 
   @vote = votes.create({:user => user})
    
    self.vote_count += 1
    
    user.add_points_for_action(:support_issue)
    supporters = votes.map{|v|v.user} 
    supporters.each do|supporter|
      case supporter
      when user
        puts "#do nothing "
      when creator
        supporter.add_points_for_action(:other_supports_issue)
      else 
        supporter.add_points_for_action(:other_supports_supported_issue)
      end
    end
    user.save!
  end
  
  def add_free_vote_for
    @vote = votes.create({:user => User.find_by_email('admin@kajoo.org')})
  end

  protected
  
    ##update fields when issue gets resolved
    def set_resolved_at
      if(resolved && resolved_at.nil?)
        resolved_at = Time.now.to_datetime
        #resolver ||= current_user
      end
    end
  
end


# == Schema Information
#
# Table name: issues
#
#' id             :integer         not null, primary key
#  title          :string(255)
#  description    :text
#  lat            :float
#  lon            :float
#  radius         :integer
#  created_at     :datetime
#  updated_at     :datetime
#  address        :string(255)
#  resolved       :boolean
#  ip_address     :string(255)
#  location       :text
#  city           :string(255)
#  state          :string(255)
#  country_code   :string(255)
#  country_name   :string(255)
#  street_address :string(255)
#  zipcode        :string(255)
#  vote_count     :integer         default(0)
#

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:show]

  #custom exception handler puts errors in the pop-down flash area
  rescue_from(VoteException) do |e|
    #TODO: Flash something?
    
    flash[:alert] = e.inspect
    logger.error "Error: '#{e.message}'"
    e.backtrace
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { 
        render :update do |page| 
          page.redirect_to(:back)
        end
      }
    end
  end
  def create
    @issue = Issue.new(params[:issue])
    if @issue.save
      current_user.add_points_for_action(:report_issue)
    end

  end

  def show 
    @issue  = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @issue }
    end
    
  end
  #XXX TODO: ajax
  def vote
    
    @issue = Issue.find(params[:id])
      
    if(IssueVote.find_by_issue_id_and_user_id(@issue.id, current_user.id))
      flash[:alert] = 'You cannot vote for the same issue twice'
      logger.warn(flash[:alert])

      respond_to do |format|
        format.html { redirect_to :back }
        format.js { 
          render :update do |page| 
            page.redirect_to(:back)
          end
        }
      end

      return
    end
    
    #@issue.add_vote_for_user(current_user)
    if(current_user.votes_remaining > 0)
       
      @issue.add_vote_for_user(current_user)
       flash[:notice] = "Thank you - your vote for '#{Profanalyzer.filter(@issue.description).slice(0,30)+'...'}' has been received"
    
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = e.inspect
      puts e.backtrace
      logger.warn(flash[:alert])
      
      respond_to do |format|
        format.html { 
          if(request.env["HTTP_REFERER"])
            redirect_to :back 
          end
        }
        format.js { 
          render :update do |page| 
            if(request.env["HTTP_REFERER"])
              page.redirect_to(:back)
            end
          end
        }
      end
    end
  end
  def index
    get_issues
  end


  def mark_resolved
    @issue = Issue.find(params[:id])
    if params[:attributed_to]
      @issue.attributed = User.find(params[:attributed_to])
    end
    if params[:solved_with]
      @issue.solution = Solution.find(params[:solved_with])
    end
    @issue.resolver_id = current_user.id
    @issue.resolved = true
          
    if @issue.save
      respond_to do |format|
         flash[:notice] = "Thank you - #{Profanalyzer.filter(@issue.description).slice(0,30)+'...'} has been resolved"

         format.html {  redirect_to(root_path)}
         format.js

      end
      else
         flash[:alert] = "whoa there buddy"
         redirect_to root_path
      end
  end

  def tag_cloud
    @tags = Issue.tag_counts_on(:discovered)
  end
  
  
end

app/helpers/issues_helper.rb
module IssuesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/issues/_action_rail.html.erb
test
<ul>
    <% if(current_user && ( current_user == issue.creator || current_user.has_voted_for_issue?(issue))) %>
      <li class="supported"><%= link_to 'Supported', user_path(current_user.twitter_id), :remote => true, :class => 'issue-vote-link disabledlink', :id => "issue-vote-link-#{issue.id}" %></li>
      <li><%= link_to 'Add Details', {:controller=>'reports', :action=>'new', :issue=>issue.id}, :remote => !is_mobile_device?, :class => 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
    <% elsif current_user %>
      <li><%= link_to 'Support this', vote_for_issue_path(issue.id), :remote => true, :class => issue.resolved? ? 'issue-vote-link disabledlink' : 'issue-vote-link', :id => "issue-vote-link-#{issue.id}" %></li>
      <li><%= link_to 'Support with Details', {:controller=>'reports', :action=>'new', :issue=>issue.id}, :remote => !is_mobile_device?, :class =>  issue.resolved? ? 'new-report-link disabledlink' : 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
    <% end %>
    <% if current_user && !issue.resolved? %>
      <li><%= link_to 'Propose Solution', new_issue_solution_path(issue), :remote => !is_mobile_device?,  :class => 'new-issue-suggestion-link', :id => "new-issue-suggestion-link-#{issue.id}" %></li>
      <li><%= link_to 'Mark Resolved', resolve_issue_path(issue.id), :remote => true, :class => 'issue-resolve-link', :id => "issue-resolve-link-#{issue.id}" %></li>
    <% elsif current_user %>
      <li>Reported As Fixed</li>
      <li><%= link_to 'Agree!', resolve_issue_path(issue.id), :remote => true, :class => current_user.id == issue.resolver_id ? 'issue-resolve-link disabledlink' : 'issue-resolve-link', :id => "issue-resolve-link-#{issue.id}" %></li>
    <% end %>
  </ul>

app/views/issues/_brief.html.erb
<div class="report_details grid_8">

  <h4><%= link_to truncate(Profanalyzer.filter(issue.description),:length => 30), issue_path(issue) %> </h4>
 <h6><%= issue.street_address %> <%= summary_date(issue.created_at) %></h6>
 <%= issue.reports.first.report_image? ? image_tag(issue.reports.first.report_image.tiny.url) : '' %>
 <p><%= Profanalyzer.filter issue.description %></p>
</div>
<div class="report_stats grid_6">
  <p class="user">
    Created By
    <%= image_tag issue.creator.avatar_url %> <%= link_to "@#{issue.creator.twitter_username}", user_path(issue.creator) %>
  </p>
  <p class="stat">
  Votes: <%= issue.votes.count %><br />
    <%= Geocoder::Calculations.distance_between(issue.lat, issue.lon, user_lat, user_lon, {:units => distance_units}).to_i %> <%= distance_units_name %>
  </p>
</div>
<div class="report_actions">
<%= render :partial => 'issues/action_rail', :locals => {:issue => issue, :order => @order} %>
</div><!--Closes report_actions-->
<div class="clear"></div>

app/views/issues/_common.html.erb
	<h5>Most Common Reports</h5>
		<ul class="most_stat">
		<li><div class="label">Pot Holes</div>
		<p class="stat_number">240</p></li>
		<li><div class="label">Pot Holes</div>
		<p class="stat_number">240</p></li>
		<li><div class="label">Pot Holes</div>
		<p class="stat_number">240</p></li>
		<li><div class="label">Pot Holes</div>
		<p class="stat_number">240</p></li>							
		</ul>

app/views/issues/_dashboard_list.html.erb
<!-- main content -->
<div id="filter">
	<ul>
	<% #XXX TODO there must be a better way to do this
	 if(is_mobile_device?)
	   latest_label = 'Recent'
	   nearest_label = 'Nearest'
	   voted_label = 'Rating'
	   resolved_label = 'Resolved'
	 else
	   latest_label = 'Most Recent'
	   nearest_label = 'Nearest to Me'
	   voted_label = 'Most Voted'
	   resolved_label = 'Recently Resolved'
	 end
	%>
	
		<li><%= link_to latest_label, {:order => 'latest'}, :class => (order == 'latest') ? 'active' : '' %></li>
		<li><%= link_to nearest_label, {:order => 'near'}, :class => (order == 'near') ? 'active' : '' %></li>
		<li><%= link_to voted_label, {:order => 'votes'}, :class => (order == 'votes') ? 'active' : '' %></li>
		<li><%= link_to resolved_label, {:order => 'resolved'}, :class => (order == 'resolved') ? 'active' : '' %></li>
	</ul>
</div><!--Closes filter navigation-->

	<h1>Browse Submitted Issues</h1>
	 <div id="report_sum"><!--STARTS: report summaries-->
    <%= !@nearpaged.nil? ? paginate(@nearpaged, :num_pages => (@issues.length.to_f / 10)) : paginate(@issues)  %>  

    <% @issues.each do |issue| %>
      <%= render :partial => 'issues/brief', :locals => {:issue => issue, :order => @order} %>
    <% end %>

  <%= !@nearpaged.nil? ? paginate(@nearpaged, :num_pages => (@issues.length.to_f / 10)) : paginate(@issues)  %>  


  </div><!--Closes report summaries-->

</div><!--Closes Main Content-->

app/views/issues/_map.html.erb
<div id="similar_reports" class="grid_10">


 <script>
    $(document).ready(function(){
    var myOptions = {
	      zoom: 4,
	      mapTypeControl: true,
	      mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
	      navigationControl: true,
	      navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
	      mapTypeId: google.maps.MapTypeId.ROADMAP      
	    }	

  	map = new google.maps.Map(document.getElementById("issue_map"), myOptions);
  	
  	initialize();
  });
function initialize()
{
  
  var lat = <%= @issue.lat %>;
  var lon = <%= @issue.lon %>;
  var address = Kajoo.Location.getUserAddress();	
  var pos=new google.maps.LatLng(lat,lon);
  var geocoder = new google.maps.Geocoder();
 
  map.setCenter(pos);
	map.setZoom(14);

  var infowindow = new google.maps.InfoWindow({
	    content: "<strong>yes</strong>"
	});
	var marker = new google.maps.Marker({
	    position: pos,
	    map: map,
      title:"You are here"
	});

}




</script>
 <div id="current"></div>
<div id="issue_map" class="grid_10"></div>

</div>

app/views/issues/index.html.erb
<%= render :partial => 'issues/dashboard_list', :locals => {:issues => @issues, :order => @order} %>

<% content_for(:feature) do %>
	<% render :partial => 'pages/index_feature' %>
<% end %>

<% content_for(:sidebar) do %>
  <% if !is_mobile_device? %>
    <% render :partial => 'shared/sidebar' %>
  <% end %>
<% end %>

app/views/issues/mark_resolved.js.erb
<%= render :partial => 'shared/close_alerts' %>

$('#issue-resolve-link-<%= @issue.id %>')
  .html('Resolved!')
  .parent().addClass('resolved supported');
  
$('#reputation-points').html('<%= current_user.points %>');

app/views/issues/show.html.erb
<%= render :partial => 'map', :locals => {:issue => @issue} %>

<% content_for(:feature) do %>  
  <div id="single_issue_feature" class="grid_16"><!--feature left starts-->
  	<h5><%= @issue.street_address %></h5>
  	<p><%= Profanalyzer.filter @issue.description %></p>
  </div><!--Closes feature left content-->
  
  <div id="single_issue_sidebar" class="grid_6"><!--feature left starts-->
  <h5>Current Supporters</h5>
		<div id="city_reports">
  		<div class="votes">
  			<span><%= @issue.supporters.count %></span><%= link_to 'Support this', vote_for_issue_path(@issue.id), :remote => true, :class => 'issue-vote-link', :id => "issue-vote-link-#{@issue.id}" %>
  		</div>
			<div id="issue_stats">
				<div class="label">Originally Reported</div>			
				<div class="date"><%#= summary_date(@issue.created_at) %></div>				
			</div><!--close city_reports-->
			<div id="issue_map" class="grid_6" style="height: 200px;">
        
			</div>
		</div>	
	</div><!--Closes feature left content-->
<% end %>

<% content_for(:sidebar) do %>
<div class="sidebar_section">
  <h5>Most Supported Issues</h5>
		<p><a	href="#">Testing Links</a> lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>
</div>	

<div class="clear"></div>			
<div class="sidebar_section">
<% render :partial => 'common' %>
</div><!--Closes sidebar-->
<% end %>

<h1>Additional Reports &amp; Suggested Solutions</h1>

<% @issue.reports.each do |report| %>
  <div class="report_sum" class="">
    <div class="text_description">		
  	<p class="date"><%= @issue.street_address %> <%= summary_date(@issue.created_at) %></p>	
  	<p><%= Profanalyzer.filter report.description %></p>
	</div>
	<div class="clear"></div>
</div>
<% end %>

app/views/issues/vote.js.erb
<%= render :partial => 'shared/close_alerts' %>

$('#issue-vote-link-<%= @issue.id %>')
  .html('Supported!')
  .parent().addClass('supported');
  
$('#votes-remaining').html('<%= current_user.votes_remaining %>');
$('#reputation-points').html('<%= current_user.points %>');