config/routes.rb
Kajoo::Application.routes.draw do
  
  resources :issues do 
    #resource :solution
    resources :suggestions, :as => 'solutions'
    #, :as => 's'
    #disabled for now
    #match 'suggestions/:id/new'
    #match 'solutions/:id/vote' => 'solutions#vote', :as => 'vote_for_solution'
    #resources :comments
  end

  match 'issues/:id/vote' => 'issues#vote', :as => 'vote_for_issue'
  match 'issues/:id/mark_resolved' => 'issues#mark_resolved',:as => 'resolve_issue'
  resources :reports
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }
  match 'users/:userid' => 'users#show', :as => 'user'


  match 'index' => "pages#index", :as => 'index'
  match 'dashboard' => 'pages#dashboard', :as => 'dashboard'
  match 'home' => 'pages#home', :as => 'home'
  match 'contact' => 'pages#contact', :as => 'contact'
  match 'about' => 'pages#about', :as => 'about'
  match 'helpus' => 'pages#helpus', :as => 'helpus'
  match 'help' => 'pages#help', :as => 'help'

#  get "users/dashboard"
  
  resources :users
  
  match 'user/location' => 'users#location'
  match 'user/address' => 'users#address'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "pages#index"

end

app/views/shared/_close_alerts.js.erb
<% if !flash[:notice].nil? %>
  $("#flash_notice").html("<%= escape_javascript(raw('<div class="flash_message_body">'+flash[:notice]+'</div>'))%>").show();
<% end %>
<% if !flash[:alert].nil? %>
  $("#alert_notice").html("<%= escape_javascript(raw('<div class="flash_message_body">'+flash[:alert]+'</div>'))%>").show();
<% end %>
$('#notices').slideDown(1000).delay(2000).slideUp(1000);

app/views/shared/_instruction_text.html.erb
<p>Click "Support This" to vote for the issues you think are the most important. The issues with the most votes will get the most attention. You can place 5 votes per day, so come back daily!</p>
<p>Earn more points by submitting issues, voting, fixing problems and getting other people to view the issues you share. Be the first to report an issue to score the most points.</p>

app/views/shared/_issues.erb
<!-- main content -->
<div id="filter">
		<ul>
  		<li><%= link_to 'Most Recent', {:order => 'latest'}, :class => (order == 'latest') ? 'active' : '' %></li>		
  		<li><%= link_to 'Most Voted', {:order => 'votes'}, :class => (order == 'votes') ? 'active' : '' %></li>		
  		<li><%= link_to 'Recently Resolved', {:order => 'resolved'}, :class => (order == 'resolved') ? 'active' : '' %></li>				
		</ul>

		</div><!--Closes filter navigation-->


		<h1>Browse Submitted Issues</h1>

    <div id="report_sum"><!--STARTS: report summaries-->
    <% issues.each do |issue| %>
      <div class="report_details">
      <h4><%= link_to issue.title, issue %></h4>
        <h6><%= issue.street_address %> <%= summary_date(issue.created_at) %></h6>
        <%#= image_tag :source => '', :style => " width='50px' height='50px'" %>
    		<p><%= issue.description %></p>
  		</div>
  		<div class="report_stats">
  		  <p class="stat">Votes: <%= issue.votes.count %></p>
  		</div>
			<div class="report_actions">
  			<ul>
  			  <% if(current_user && current_user.has_voted_for_issue?(issue)) %>
            <li class="supported"><a href="#">Supported!</a></li>
            <li><%= link_to 'Add Details', new_report_path, :remote => true, :class => 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
  			  <% else %>
      			<li><%= link_to 'Support this', vote_for_issue_path(issue.id), :remote => true, :class => 'issue-vote-link', :id => "issue-vote-link-#{issue.id}" %></li>
      			<li><%= link_to 'Support with Details', new_report_path, :remote => true, :class => 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
    			<% end %>
    			
    			<li><a href="#">Propose Solution</a></li>
    			<% if !issue.resolved %>
      			<li><a href="#">Mark Resolved</a></li>			
    			<% end %>
  			</ul>
			</div><!--Closes report_actions-->
			<div class="clear"></div>
    <% end %>
    </div><!--Closes report summaries-->

</div><!--Closes Main Content-->

app/views/shared/_issues.html.erb
<!-- main content -->
<div id="filter">
	<ul>
	<% #XXX TODO there must be a better way to do this
	 if(is_mobile_device?)
	   latest_label = 'Recent'
	   nearest_label = 'Nearest'
	   voted_label = 'Rating'
	   resolved_label = 'Resolved'
	 else
	   latest_label = 'Most Recent'
	   nearest_label = 'Nearest to Me'
	   voted_label = 'Most Voted'
	   resolved_label = 'Recently Resolved'
	 end
	%>
	
		<li><%= link_to latest_label, {:order => 'latest'}, :class => (order == 'latest') ? 'active' : '' %></li>
		<li><%= link_to nearest_label, {:order => 'near'}, :class => (order == 'near') ? 'active' : '' %></li>
		<li><%= link_to voted_label, {:order => 'votes'}, :class => (order == 'votes') ? 'active' : '' %></li>
		<li><%= link_to resolved_label, {:order => 'resolved'}, :class => (order == 'resolved') ? 'active' : '' %></li>
	</ul>
</div><!--Closes filter navigation-->

	<h1>Browse Submitted Issues</h1>
	<%= paginate @issues, :window => 2 %>  
  <div id="report_sum"><!--STARTS: report summaries-->


    <% @issues.each do |issue| %>
      <div class="report_details grid_8">
       <h4><%= link_to issue.title, issue %></h4>
        <h6><%= issue.street_address %> <%= summary_date(issue.created_at) %></h6>
        <%#= image_tag :source => '', :style => " width='50px' height='50px'" %>
    		<p><%= issue.description %></p>
  		</div>
  		<div class="report_stats grid_6">
  		  <p class="user">
  		    Created By
  		    <%= image_tag issue.creator.avatar_url %> <%= link_to "@#{issue.creator.twitter_username}", user_path(issue.creator) %>
  		  </p>
  		  <p class="stat">
        Votes: <%= issue.votes.count %><br />
  		    <%= Geocoder::Calculations.distance_between(issue.lat, issue.lon, user_lat, user_lon, {:units => distance_units}).to_i %> <%= distance_units_name %>
  		  </p>
  		</div>
  		<div class="report_actions">
  			<ul>
  			  <% if(current_user && current_user.has_voted_for_issue?(issue)) %>
            <li class="supported"><%= link_to 'Supported', vote_for_issue_path(issue.id), :remote => true, :class => 'issue-vote-link', :id => "issue-vote-link-#{issue.id}" %></li>
            <li><%= link_to 'Add Details', {:controller=>'reports', :action=>'new', :issue=>issue.id}, :remote => !is_mobile_device?, :class => 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
  			  <% else %>
      			<li><%= link_to 'Support this', vote_for_issue_path(issue.id), :remote => true, :class => 'issue-vote-link', :id => "issue-vote-link-#{issue.id}" %></li>
      			<li><%= link_to 'Support with Details', {:controller=>'reports', :action=>'new', :issue=>issue.id}, :remote => !is_mobile_device?, :class => 'new-report-link', :id => "new-report-link-#{issue.id}" %></li>
    			<% end %>
           <li><%= link_to 'Propose Solution', new_issue_solution_path(issue), :remote => !is_mobile_device?,  :class => 'new-issue-suggestion-link', :id => "new-issue-suggestion-link-#{issue.id}" %></li>

        <%#<li><a href="#">Propose Solution</a></li>%>
        <% if !issue.resolved %>
          <li><%= link_to 'Mark Resolved', resolve_issue_path(issue.id), :remote => true, :class => 'issue-resolve-link', :id => "issue-resolve-link-#{issue.id}" %></li>
 
  			<% end %>
  			</ul>
  		</div><!--Closes report_actions-->
      <div class="clear"></div>
    <% end %>
 
  </div><!--Closes report summaries-->

</div><!--Closes Main Content-->

app/views/shared/_navigation.erb
<!--<h1><%= link_to "Kajoo #{city_name} : #{site_name}", root_path %></h1>-->


<div class="grid_10">
<a  href="/" id="logo"><img src="/images/kajoo-logo-lockup.png" height="100" width=""></a>
</div>

<div id="navigation" class="grid_14 omega">
	<ul>
	   <% if is_mobile_device? 
	     home_label = 'Home'
	     votes_label = 'Votes'
	     rep_label = 'Reputation'
	   else
  	   home_label = 'Home' 
	     votes_label = 'Votes Remaining'
	     rep_label = 'Reputation Points'
	   end %>
	
	   <% if(current_user) %>
		  <li><%= link_to home_label, root_path %></li>
      <li><%= link_to raw("<span id=\"votes-remaining\">#{current_user.votes_remaining}</span> #{votes_label}"), users_dashboard_path %></li>
      <li><%= link_to raw("<span id=\"reputation-points\">#{current_user.points}</span> #{rep_label}"), users_dashboard_path %></li>
  	  <li><img id="twitter_avatar" src="<%= current_user.avatar_url %>" alt="<%= current_user.name %>">
    	  <% if !is_mobile_device? %><%= link_to current_user.name, user_path(current_user), :id => 'account_link' %> | <% end %>
    	  <%= link_to 'Logout', destroy_user_session_path, :id => 'logout_link' %></li>
		<% else %>
  		<li><%= link_to "View Issues", issues_path %></li>
		  <li><%= link_to "Login", user_omniauth_authorize_path(:twitter), :id => 'login' %></li>
		<% end %>
	</ul>
</div>

app/views/shared/_navigation.html.erb
<!--<h1><%= link_to "Kajoo #{city_name} : #{site_name}", root_path %></h1>-->


<div class="grid_8">
  <a  href="/" id="logo">
    <% if is_mobile_device? %>
      <img src="/images/logo_small.png">
    <% else %>
      <img src="/images/logo_med.png">
    <% end %>
  </a>
</div>

<div id="navigation" class="grid_16 omega">
	<ul>
	   <% if is_mobile_device? 
	     home_label = raw('&#x2302;')
	     votes_label = 'Votes'
	     rep_label = 'Reputation'
	     city_label = 'City'
	   else
  	   home_label = 'Home' 
	     votes_label = 'Votes Left'
	     rep_label = 'Reputation'
	     city_label = 'City View'
	   end %>
	
	   <% if(current_user) %>
		  <li><%= link_to home_label, root_path, :id => 'home_link' %></li>
		  <li><%= link_to city_label, dashboard_path %></li>
      <li><%= link_to raw("<span id=\"votes-remaining\">#{current_user.votes_remaining}</span> #{votes_label}"), user_path(current_user.twitter_username) %></li>
      <li><%= link_to raw("#{rep_label} : <span id=\"reputation-points\">#{current_user.points}</span>"), user_path(current_user.twitter_username) %></li>
      <li><%= link_to "Report", new_report_path, :id => 'create-report-link', :remote => !is_mobile_device? %></li>
       <li><img id="twitter_avatar" src="<%= current_user.avatar_url %>" alt="<%= current_user.name %>">
    	  <% if !is_mobile_device? %><%= link_to current_user.name, user_path(current_user.twitter_username), :id => 'account_link' %> | <% end %>
    	  <%= link_to 'Logout', destroy_user_session_path, :id => 'logout_link' %></li>
		<% else %>
  		<li><%= link_to home_label, root_path, :id => 'home_link' %></li>
  		<li><%= link_to city_label, dashboard_path %></li>
  		<li><%= link_to "View Issues", issues_path %></li>
		  <li><%= link_to "Login", user_omniauth_authorize_path(:twitter), :id => 'login' %></li>
		<% end %>
		<li id="location">no location</li>
	</ul>
</div>

app/views/shared/_sample_feature_old.html.erb
<div class="flipsummary"><!--feature left starts-->	
  <h1>Remove the Monster Gator threat</h1>
  <p>
   <%= image_tag "http://media.kvue.com/images/600*805/1gator030811.jpg", :style => 'height: 100px; float: left; padding: 4px;' %>
 
   Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus tempizzle pimpin'. 
   Mauris pellentesque nibh shiz mah nizzle. Crackalackin gangster tortizzle. Pellentesque shizzlin dizzle yippiyo nisi. In ma nizzle own yo' platea dictumst. 
  </p>
  <% if(current_user) %>
    <%= link_to "Submit A Report", new_report_path %>
  <% else %>
     <%= link_to "Sign Up",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %>
  <% end %>
</div><!--Closes feature left content-->
<div class="flipsummary"><!--feature left starts-->	
  <h1>Moon attacks! What can be done? </h1>
  <p>
   <%= image_tag "http://cache.gawker.com/assets/images/gawker/2009/07/ww.jpg
", :style => 'height: 100px; float: left; padding: 4px;' %>
 
   Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus tempizzle pimpin'. 
   Mauris pellentesque nibh shiz mah nizzle. Crackalackin gangster tortizzle. Pellentesque shizzlin dizzle yippiyo nisi. In ma nizzle own yo' platea dictumst. 
  </p>
  <% if(current_user) %>
    <%= link_to "Submit A Report", new_report_path %>
  <% else %>
     <%= link_to "Sign Up",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %>
  <% end %>
</div><!--Closes feature left content-->

app/views/shared/_sidebar.erb
  <h3>Notifications</h3>
	<p>Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>
	
	<h3>Leaderboard</h3>
	<p>Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>

app/views/shared/_sidebar.html.erb
  <div class="sidebar_section" class="grid_6">
    <% if(current_user) %>
      <div class="button"><%= link_to "Submit A Report", new_report_path, :id => 'create-report-link' %></div>
    <% else %>
      <div class="button"><%= link_to "Sign Up",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %></div>
    <% end %>
  </div>

  <h3>Notifications</h3>
	<p>Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>
	
	<h3>Leaderboard</h3>
	<p>Lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>

app/views/shared/_user.html.erb
<%= image_tag @user.avatar_url %> <%= @user.twitter_username %>

app/views/shared/_version.html.erb
  <% if(!version.initial?) %>
    <li>
      <% issue = Issue.find(version.versioned_id) %>
      <b><%= link_to  truncate(Profanalyzer.filter(report.description), :length => 30),  issue %> version <%= version.number %> </b>
      <p>Date: <%= version.created_at %></p>
      <% if(!version.user_id.nil?) %>
        <% user = User.find(version.user_id) %>
        <p>User: <%= link_to user.name, user %> </p>
      <% end %>
      <p>Changes: 
        <table class="changes">
          <% version.modifications.each do |field, change| %>
            <tr><th><%= field %></th><td><%= change[1] %></td></tr>
          <% end %>
        </table>
      </p>
    </li>
  <% end %>

app/views/shared/exeption.html.erb
Exception