config/routes.rb
Kajoo::Application.routes.draw do
  
  resources :issues do 
    #resource :solution
    resources :suggestions, :as => 'solutions'
    #, :as => 's'
    #disabled for now
    #match 'suggestions/:id/new'
    #match 'solutions/:id/vote' => 'solutions#vote', :as => 'vote_for_solution'
    #resources :comments
  end

  match 'issues/:id/vote' => 'issues#vote', :as => 'vote_for_issue'
  match 'issues/:id/mark_resolved' => 'issues#mark_resolved',:as => 'resolve_issue'
  resources :reports
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }
  match 'users/:userid' => 'users#show', :as => 'user'


  match 'index' => "pages#index", :as => 'index'
  match 'dashboard' => 'pages#dashboard', :as => 'dashboard'
  match 'home' => 'pages#home', :as => 'home'
  match 'contact' => 'pages#contact', :as => 'contact'
  match 'about' => 'pages#about', :as => 'about'
  match 'helpus' => 'pages#helpus', :as => 'helpus'
  match 'help' => 'pages#help', :as => 'help'

#  get "users/dashboard"
  
  resources :users
  
  match 'user/location' => 'users#location'
  match 'user/address' => 'users#address'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "pages#index"

end

app/views/pages/_dashboard_sidebar.html.erb
<div class="sidebar_section" class="grid_6">
  <h5>Most Supported Issues</h5>
  <p><a	href="#">Testing Links</a> lorizzle ipsizzle dolor the bizzle amizzle, ma nizzle adipiscing elit. Nullam sapien velit, gangsta volutpizzle, pot black, gravida vizzle, . Pellentesque rizzle tortizzle. Sizzle erizzle. Ma nizzle at dolor dapibus suscipit. Mah nizzle black velit sizzle mammasay mammasa mamma oo sa.</p>
</div>	
		
<div class="clear"></div>			
<div class="sidebar_section">
		<h5>Most Common Reports</h5>
		<ul class="most_stat">
 <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
   <li><%= tag.name %><%#= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %></li>	
  <% end %>
  
  
      <li><div class="label">Pot Holes</div>
		<p class="stat_number">240</p></li>							
		</ul>
</div><!--Closes sidebar-->

</div><!--Closes notifications-->
<div class="clear">

app/views/pages/_index_feature.html.erb
<% if current_user %>
  <!--LOGGED IN-->
  <h1>Let's build a great city together!</h1>
  <% if !is_mobile_device? %>
    <%= render :partial => 'shared/instruction_text' %>
  <% end %>      
  <div class="button"><%= link_to "Submit A Report", new_report_path, :id => 'create-report-link', :remote => !is_mobile_device? %></div>
  <div class="button"><%= link_to "About this Site", help_path, :id => 'help-link' %></div>
<% else %>
  <!--NOT LOGGED IN-->
  <% if is_mobile_device? %>
  
    <h1>Welcome to Kajoo</h1>
    <p>Kajoo is a civic engagement platform in which citizens collaborate to improve their city. You report problems in your city, vote on the top problems and the community works together to solve them.</p>

    <div class="button"><%= link_to "Get Started", user_omniauth_authorize_path(:twitter), :id => 'sign_up' %></div>
  <% else %>
  
    <div id="home_pitch" class="grid_11">
      <h1>Welcome to Kajoo</h1>
      <p>Kajoo is a civic engagement platform in which citizens collaborate to improve their city. You report problems in your city, vote on the top problems and the community works together to solve them.</p>
      Try these:
      <ul>
        <li>Beautifying a park</li>
        <li>Fixing or sealing roads</li>
        <li>Turning a vacant lot into a community garden</li>
      </ul>
      <p><strong>Watch our video to hear what folks in Austin, Texas would change about the city they love</strong></p>
      <div class="button"><%= link_to "Get Started", user_omniauth_authorize_path(:twitter), :id => 'sign_up' %></div>
    </div>
    <div id="home_video" class="grid_11 omega">
      <iframe src="http://player.vimeo.com/video/20919967" class="grid_12" height="270" frameborder="0"></iframe>
    </div>
  <% end %>
<% end %>

app/views/pages/about.html.erb
<h1>About TODO</h1>

app/views/pages/contact.html.erb
<h1>Contact TODO</h1>

app/views/pages/dashboard.html.erb
<% content_for :head do %>

  <script type="text/javascript">
      var marker_resultset = <%= @issue_markers.html_safe %>
  </script>
<% end %>
 <script>
    $(document).ready(function(){
    var myOptions = {
	      zoom: 4,
	      mapTypeControl: true,
	      mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
	      navigationControl: true,
	      navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
	      mapTypeId: google.maps.MapTypeId.ROADMAP      
	    }	

  	map = new google.maps.Map(document.getElementById("city_map"), myOptions);
  	
  	initialize();
  });

	
  function initialize()
  {

      var lat = getUserLat();
      var lon = getUserLon();
      var address = getUserAddress();	
      var pos=new google.maps.LatLng(lat,lon);
      var geocoder = new google.maps.Geocoder();
     
      map.setCenter(pos);
      map.setZoom(14);


  	if(geo_position_js.init())
  	{
  		$('#current_location').html("<img src=\"/images/spinner.gif\"/> finding location...");
  		geo_position_js.getCurrentPosition(show_position,function(){$('#current_location').html("Couldn't get location")},{enableHighAccuracy:true});
  	}
  	else
  	{
  		$('#current_location').html("Functionality not available");
  	}
  }
  
  function show_position(p)
  {
    geocoder = new google.maps.Geocoder();
    var pos=new google.maps.LatLng(p.coords.latitude,p.coords.longitude);
    map.setCenter(pos);
  	map.setZoom(14);
  	
  	geocoder.geocode({'latLng': pos}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        $('#current_location').html(results[1].formatted_address);
      }
    });

  	var marker = new google.maps.Marker({
  	    position: pos,
  	    map: map,
  	    title:"You are here"
  	});
  
  	google.maps.event.addListener(marker, 'click', function() {
  	  infowindow.open(map,marker);
  	});
  	
  	marker.click();
  }
  </script>


<% content_for(:feature) do %>
	<div id="map" class="grid_16"><!--feature left starts-->
	<h5>Issues Around <%= city_name %>, <%= state_name %></h5>
	<p id="current_location"></p>
	<div id="city_map"></div>

	</div><!--Closes feature left content-->
<div id="city_status" class="grid_6"><!--feature left starts-->
<h5>How is <%= city_name %> Doing?</h5>

		<div id="city_reports">
		
		<div class="label">Reports Submitted</div>			
		<p><a href="#"><%= @submitted_reports %></a></p>
		<div class="label">Reports Resolved</div>			
		<p><a href="#"><%= @resolved_reports %></a></p>
		<div class="label">Caring Users</div>			
		<p><a href="#" alt="Austin,TX Leaderboard"><%= @user_count %></a></p>
				
		</div><!--close city_reports-->
		<div class="label">City Lifeline</div>
		<div id="city_lifeline">
		<img src="<%= raw @submissions_chart_url %>" width="250" height="100" />
		</div>	
	
</div><!--Closes feature left content-->	
<% end %>

<% content_for(:sidebar) do %>
  <% render :partial => 'dashboard_sidebar' %>
<% end %>

<%= paginate @issues, :window => 2, :num_pages =>  (@nearissues.length.to_f / 10)  %>  
<%#= paginate @issues, :window => 2 %>  


<%= render :partial => 'issues/dashboard_list', :locals => {:issues => @issues, :order => @order} %>
<%#= paginate @issues, :window => 2, :num_pages =>  ( @issue_pages.count.to_f / 10)  %>  
<%= paginate @issues, :window => 2, :num_pages =>  (@nearissues.length.to_f / 10)  %>  
<%= content_for(:foot) do %>
  <%#= javascript_include_tag "markerclusterer_packed" %>
<% end %>

app/views/pages/help.html.erb
<% content_for(:feature) do %>
  <h1>Help</h1>
  <p>Click "Support This" to vote for the issues you think are the most important. The issues with the most votes will get the most attention. You can place 5 votes per day, so come back daily!</p>
  <p>Earn more points by submitting issues, voting, fixing problems and getting other people to view the issues you share. Be the first to report an issue to score the most points.</p>

  <div class="button"><%= link_to "Let's get Started!", root_path, :id => 'home-link' %></div>
<% end %>

app/views/pages/helpus.html.erb
<% content_for(:feature) do %>
  <h2>We're Kajoo. We're new here. We need your help!</h2>	
  <p>We're trying to put tools for civic engagement in the hands of as many people as possible. It's not easy, but with your help it's possible. Take 5 minutes out of your day to do any of the things below, and know that you've helped make the world a little bit better.</p>
<% end %>

<% content_for(:sidebar) do %>
  <% render :partial => 'shared/sidebar' %>
<% end %>


<ul id="waystohelp">
<li><strong>Socialites &rarr;</strong> <em>Send this page</em> to any friends who may be interested! Particularly people in the media, or others at SXSW who may wish to help.</li>
<li><strong>Investors &rarr;</strong> <em>Buy "virtual shares" in Kajoo</em> at <a href="http://startupbus.com/game/startup_game_profiles/79-kajoo-org">The StartupBus Investment Game</a>.</li>
<li><strong>Ruby Coders &rarr;</strong> <b>Fork the code</em> for your own city at <a href="https://github.com/mjording/kajoo">on GitHub</a>, and send pull requests for cool new features. Cities that build working, usable systems will get their own subdomain at [mycity].kajoo.org.</li>
<li><strong>Twitterati &rarr;</strong> Tweet about Kajoo! Click here: <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://kajoo.org" data-text="I just joined #kajoo, the Open Source civic engagement platform. Fix the city you love." data-count="horizontal" data-via="kajooit" data-related="xero:Xero: StartupBus Sponsors">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></li>
<li><strong>Bring us Open Data &rarr;</strong> We want connections to open civic data systems and organisations so that we can fill Kajoo with existing issues that people can <em>act on today</em>.
<li><strong>Ideas ideas ideas &rarr;</strong> Bring us your ideas, but better yet <em><a href="https://github.com/mjording/kajoo">your code</a></em>. 
</ul>

app/views/pages/index.erb
<% content_for(:feature) do %>
	<% render :partial => 'shared/home_feature' %>
<% end %>

<% content_for(:sidebar) do %>
  <% if !is_mobile_device? %>
    <% render :partial => 'shared/sidebar' %>
  <% end %>
<% end %>

<%= render :partial => 'shared/issues', :locals => {:issues => @issues, :order => @order} %>

app/views/pages/index.html.erb
<%= render :partial => 'issues/dashboard_list', :locals => {:issues => @issues, :order => @order} %>

<% content_for(:feature) do %>
	<% render :partial => 'index_feature' %>
<% end %>

<% content_for(:sidebar) do %>
  <% if !is_mobile_device? %>
    <% render :partial => 'shared/sidebar' %>
  <% end %>
<% end %>

app/views/pages/index.js.erb
<%= render :partial => 'shared/close_alerts' %>

var buildForm = function(){
  var index_html = "<%= escape_javascript(render :partial => 'index_feature')%>"
  $(this).html(index_html);
};

$('#feature_content').slideUp(500, buildForm).slideDown(500);

$('#feature').scrollToMe();

app/views/pages/updates.html.erb
<h1>Latest Changes</h1>
<ul id="versions">
<% @versions.each do |version| %>
  <%= render :partial => 'shared/version', :locals => {:version => version} %>
<% end %>
</ul>