config/routes.rb
Kajoo::Application.routes.draw do
  
  resources :issues do 
    #resource :solution
    resources :suggestions, :as => 'solutions'
    #, :as => 's'
    #disabled for now
    #match 'suggestions/:id/new'
    #match 'solutions/:id/vote' => 'solutions#vote', :as => 'vote_for_solution'
    #resources :comments
  end

  match 'issues/:id/vote' => 'issues#vote', :as => 'vote_for_issue'
  match 'issues/:id/mark_resolved' => 'issues#mark_resolved',:as => 'resolve_issue'
  resources :reports
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions => "users/sessions" }
  match 'users/:userid' => 'users#show', :as => 'user'


  match 'index' => "pages#index", :as => 'index'
  match 'dashboard' => 'pages#dashboard', :as => 'dashboard'
  match 'home' => 'pages#home', :as => 'home'
  match 'contact' => 'pages#contact', :as => 'contact'
  match 'about' => 'pages#about', :as => 'about'
  match 'helpus' => 'pages#helpus', :as => 'helpus'
  match 'help' => 'pages#help', :as => 'help'

#  get "users/dashboard"
  
  resources :users
  
  match 'user/location' => 'users#location'
  match 'user/address' => 'users#address'
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "pages#index"

end

app/views/layouts/application.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<title>Kajoo <%= city_name %> : <%= site_name %> : Improve Your City</title>

  <%= javascript_include_tag 'jquery', 'rails', 'jquery.clearinginput.js', 'modernizr', 'application' %>
  
  <% if is_mobile_device? %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag 'style', 'text', 'handheld', 'kajoo_mobile' %>
  <% else %>
    <%= stylesheet_link_tag 'style', '960_24_col', 'text', 'application', 'kajoo' %>
  <% end %>  
  <%= yield(:head) %>
  <%= csrf_meta_tag %>
</head>

<body>

<div id="wrapper" class="container_24">
<% if notice %><div class="grid_24"><div class="flash_message" id="flash_notice"><%= notice %></div></div><% end %>
<% if alert %><div class="grid_24"><div class="flash_message" id="flash_alert"><%= alert %></div></div><% end %>
<div id="header" class="container_24"><!--Header starts-->
  <%= render :partial => 'shared/navigation' %>
</div><!--closes header--><div class="clear"></div>
<div id="main"><!--Content starts-->
<div class="grid_24"><!--Feature Content-->
  <div id="feature">
    <%= yield(:feature) %>		
    <div class="clear"></div>
  </div>
</div><!--Closes Feature Content--><div class="clear"></div>



<div id="main_content" class="grid_16"><!--Starts Main Content -->

    <%= yield %>
  	<div id="sidebar" class="grid_6"><!--starts sidebar-->
      <% if(current_user) %>
        <%= link_to "Submit A Report", new_report_path, :id => 'create-report-link' %>
      <% else %>
         <%= link_to "Sign Up",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %>
      <% end %>
			<%= yield(:sidebar) %>		
		
	</div>	<!--Closes sidebar-->


</div>		

	

  <div class="clear"></div>
  <div id="footer"><!--Footer starts-->
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %> 
        </li>
        <li>
          <%= link_to "View Issues", issues_path %>
        </li>
      <% if(current_user) %>
          <li><a href="#">Votes Remaining</a></li>
      <% else %>
        <li> <%= link_to "Login",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %></li>
      <% end %>
      </ul>
  </div><!--Closes Footer-->

</div><!--Closes main-->



</div><!--Closes wrapper-->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21922736-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<title>Kajoo <%= city_name %> : <%= site_name %> : Improve Your City</title>

<%= javascript_include_tag 'jquery', 'rails', 'jquery.clearinginput.js','modernizr', 'geo', 'application' %>
<script>
  default_lon = <%= SITE['lon'] %>;
  default_lat = <%= SITE['lat'] %>;
</script>
  <% if is_mobile_device? %>
    <%= javascript_include_tag 'application_mobile' %>
    <% if is_device?('iphone') %>
      <%= javascript_include_tag 'application_iphone' %>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
    <script src="http://code.google.com/apis/gears/gears_init.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= stylesheet_link_tag 'style', 'text', 'handheld', 'kajoo_mobile' %>
  <% else %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <%= stylesheet_link_tag 'style', '960_24_col', 'text', 'application', 'kajoo' %>
  <% end %>  
  <%= yield(:head) %>
  <%= csrf_meta_tag %>
</head>

<body>

<div id="wrapper" class="container_24">
<div id="notices">
  <div class="grid_24"><div class="flash_message" id="flash_notice"><% if notice %><div class="flash_message_body"><%= raw(notice) %></div><% end %></div></div>
  <div class="grid_24"><div class="flash_message" id="flash_alert"><% if alert %><div class="flash_message_body"><%= raw(alert) %></div><% end %></div></div>
</div>
<div id="header" class="container_24"><!--Header starts-->
  <%= render :partial => 'shared/navigation' %>
</div><!--closes header--><div class="clear"></div>
<div id="main"><!--Content starts-->
<div class="grid_24"><!--Feature Content-->
  <div id="feature">
    <div id="feature_content">
      <%= yield(:feature) %>		
    </div>
    <div class="clear"></div>
  </div>
</div><!--Closes Feature Content--><div class="clear"></div>



<div id="main_content" class="grid_16"><!--Starts Main Content -->

    <%= yield %>

</div>		

<div id="sidebar" class="grid_6"><!--starts sidebar-->
	<%= yield(:sidebar) %>		
</div>	<!--Closes sidebar-->

	

  <div class="clear"></div>
  <div id="footer"><!--Footer starts-->
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %> 
        </li>
        <li>
          <%= link_to "View Issues", issues_path %>
          </li>
<li class="navigation-item">
         	  <% if user_signed_in? %>
         	    Signed in as <%= current_user.email || current_user.user_name %>. Not you?
         	    <%= link_to "Sign out", destroy_user_session_path %>
         	  <% else %>
         	    <%= link_to "Sign in", new_user_session_path %> or
         	    <%#= link_to "Sign in with Github", user_omniauth_authorize_path(:github) %>
              or
            <%#= link_to "Sign in as User with meetup", user_omniauth_authorize_path(:meetup) %> or <%= link_to "sign in", new_user_session_path %>
         	  <% end %>
          
      </li>
          
      <% if(current_user) %>
          <li><a href="#">Votes Remaining</a></li>
      <% else %>
        <li> <%= link_to "Login",user_omniauth_authorize_path(:twitter), :id => 'sign_up' %></li>
      <% end %>
      </ul>
  </div><!--Closes Footer-->

</div><!--Closes main-->



</div><!--Closes wrapper-->
<%= yield(:foot) %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21922736-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>